# Generated by Django 4.2.4 on 2024-06-21 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogoEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('banco', models.CharField(max_length=50, null=True)),
                ('cuenta', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_vencimiento', models.IntegerField()),
                ('isr_aplicable', models.BooleanField(default=False)),
                ('retencion_iva_aplicable', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.catalogoemp')),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fechaPago', models.DateField()),
                ('refe', models.CharField(max_length=30, null=True)),
                ('formaPago', models.CharField(max_length=30, null=True)),
                ('movi', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noFac', models.CharField(max_length=200, null=True)),
                ('folioF', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('iva', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vencido', models.BooleanField(default=False)),
                ('en_pago', models.BooleanField(default=False)),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.empresas')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.pagos')),
            ],
        ),
    ]
